medulla-tech/medulla-agent

Doxyfile

Fix project version in doxyfile

(doc) Fix project version

---

pulse_xmpp_agent/agentxmpp.py
pulse_xmpp_agent/commadeformate
pulse_xmpp_agent/connectionagent.py
pulse_xmpp_agent/lib/configuration.py
pulse_xmpp_agent/lib/grafcetdeploy.py
pulse_xmpp_agent/lib/networkinfo.py
pulse_xmpp_agent/lib/utils.py
pulse_xmpp_agent/testconnexionxmpppulse.py

Fix wrong english spelling ( spotted by sider )

Fix spelling

---

pulse_xmpp_master_substitute/lib/plugins/glpi/Glpi84.py
pulse_xmpp_master_substitute/lib/plugins/glpi/Glpi92.py

These functions were not declared so they have been added.
Replace Glpi94 call by Glpi84 call, that was a mistake.
In the Glpi92.py file replace Glpi call by Glpi92 call.

Add missing functions into Glpi84.py file

---

pulse_xmpp_master_substitute/lib/plugins/glpi/Glpi84.py

These functions are useless in the substitute agent

Remove useless functions

---

pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_loadpluginlistversion.py

This message generates an error, so it is removed

This message generates an error

---

pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_registeryagent.py

check_uuidinventory parameter is set to False by default

Coherency control between glpi and xmpp

---

pulse_xmpp_agent/lib/configuration.py

the new user of the jid is now "hostname" decorated with a random suffix.
the resource becomes the smallest mac address.

[feature] new algorithm to establish agent's jid

---

debian/pulse-xmpp-agent.install
debian/rules

Reverts pulse-project/pulse-xmpp-agent#24

Revert "Install manage_scheduler.ini to /var/lib/pulse2/clients/config/"

---

pulse_xmpp_agent/pulse-xmpp-agent-log.py

(cherry picked from commit b5e3c03f0112403d3dabedecc4a82288db8275c4)

Start a deployment whenever a machine is available in the deployment interval

---

pulse_xmpp_master_substitute/lib/plugins/xmpp/__init__.py
pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_registeryagent.py

(cherry picked from commit 9ead14e83e9b30696208a46d6a4c1cd45af44d5e)

[guacamole] Force configuration of guacamole if no connection present

---

scripts_installer/win/agent-installer.nsi.in

(Fix) Delete only py file

---

pulse_xmpp_agent/agentxmpp.py
pulse_xmpp_master_substitute/lib/manage_process.py
pulse_xmpp_master_substitute/lib/plugins/msc/__init__.py
pulse_xmpp_master_substitute/lib/plugins/xmpp/__init__.py

This push Request handle Exception for deleting/copying files and casting number to int.

[QA] Do not use bare except to remove a file

---

pulse_xmpp_agent/agentxmpp.py
pulse_xmpp_agent/connectionagent.py
pulse_xmpp_agent/launcher.py
pulse_xmpp_agent/lib/agentconffile.py
pulse_xmpp_agent/lib/configuration.py
pulse_xmpp_agent/lib/grafcetdeploy.py
pulse_xmpp_agent/lib/manage_xmppbrowsing.py
pulse_xmpp_agent/lib/managedeployscheduler.py
pulse_xmpp_agent/lib/managepackage.py
pulse_xmpp_agent/lib/syncthingapirest.py
pulse_xmpp_agent/pluginsmachine/plugin_inventory.py
pulse_xmpp_master_substitute/lib/agentconffile.py
pulse_xmpp_master_substitute/lib/grafcetdeploy.py
pulse_xmpp_master_substitute/lib/manage_xmppbrowsing.py
pulse_xmpp_master_substitute/lib/managedbkiosk.py
pulse_xmpp_master_substitute/lib/managedeployscheduler.py
pulse_xmpp_master_substitute/lib/managepackage.py
scripts_installer/mac/postflight.in

This pull request add Darwin support
-> Change the path to /opt/Pulse
-> Add new functions ( pulseTempDir )

Add Darwin support

---

pulse_xmpp_agent/pluginsmachine/plugin_inventory.py

fixes pulse-project/siveo-todo#239

[inventory] Fix calling of functions from utils

---

pulse_xmpp_agent/agentxmpp.py
pulse_xmpp_agent/lib/xmppiq.py
pulse_xmpp_master_substitute/lib/reverseport.py
pulse_xmpp_master_substitute/lib/xmppiq.py
pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_loadpluginsubscribe.py

fixes pulse-project/siveo-todo#243

[reversessh] Create reversessh for remote file browser

---

pulse_xmpp_agent/lib/server_kiosk.py

[kiosk] Remove typo

---

pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_loaddeployment.py

Data['hash'] don't be push to descriptor, fixed

[CDN] Fix error for cdn deployment

---

pulse_xmpp_agent/lib/server_kiosk.py

- The asking sent through the kiosk arrives now to the master, now it has to be interpreted
- There were also some logs bug fixed

[kiosk] send to plugin master the information when ask button is clicked

---

pulse_xmpp_agent/agentxmpp.py
pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_evtfrommachine.py
pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_registeryagent.py

Registration is no longer dependent on presence of subscription substitute

[subscription and registration] Change the way the registration works as we are no longer registering to master@pulse

---

pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_assessor_agent.py

Make use of a list as counter. The size of the list gives the size of the counter.
The list automatically deletes the 300 seconds old expired sessions. The deletion also sends a message to remove the configuration accounts.

[assessor] smoothing of configuration processing

---

pulse_xmpp_agent/lib/managedbkiosk.py
pulse_xmpp_agent/lib/managedeployscheduler.py

Since some releases of berkeleydb there is no windows build. So we cannot build the python module.
We migrate to lmdb which is based on berkeleydb.

(python3 migration) Migrage from bsddb3 to lmdb

---

pulse_xmpp_agent/agentxmpp.py

Server make conversion from GMT to Local Timezone to set stardate and enddate variable on descripteur, but on agent, we have to reconvert time to GMT to don't have wrong check time condition when we click on false button for postpone question

(UserInteraction) Postpone question have to check time with GMT

---

pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_disable_rescue.py
pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_downloadfile.py
pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_force_setup_agent.py

A new signature for plugins called by master substitute replaces the obsolete signature of mmc master plugins.
new => def action(xmppobject, action, sessionid, data, message, dataobj)
obsolete => def action(xmppobject, action, sessionid, data, message, ret, dataobj)

(quick actions) Fix quick actions by adding the missing plugins and fixing the signature of plugins
